### ISSUE TITLE
Demo source code

### ISSUE THREAD

**Issue by HashedViking** [Zheng-Chong/FashionMatrix#1]
Hello, thank you for the awesome paper! Do you plan to release the code?

**Comment by Zheng-Chong** [comment]
Of course, we are working on improving the readability of the code, which will be released in the near future

**Comment by Zheng-Chong** [comment]
The source code and installation guide of the current version (Label 1.1) have been released. All models except LLM can run on a 13G+ single GPU. The Chat version is still being debugged, since the performance of the open source LLMs is not stable 😂
