### ISSUE TITLE
requests.exceptions.ConnectionError: HTTPConnectionPool(host='0.0.0.0', port=8123): Max retries exceeded with url: /graph (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe896d2d2d0>: Failed to establish a new connection: [Errno 111] Connection refused'))

### ISSUE THREAD

**Issue by shrinivasait** [Zheng-Chong/FashionMatrix#5]
Not able to get through the error. Please guide

**Comment by Zheng-Chong** [comment]
From the error report, your server.py did not start correctly. Please check whether your server.py is running normally. You can view the output of server.py in real time by running server.py directly instead of using nohup.

**Comment by shrinivasait** [comment]
OSError: You seem to have cloned a repository without having git-lfs installed. Please install git-lfs and run `git lfs install` followed by `git lfs pull` in the folder you cloned.

I am getting this when i run server.py.
I installed git-lfs, but though i am getting this error

**Comment by Zheng-Chong** [comment]
This shows that maybe some models downloaded from HuggingFace is missing.  Please check your checkpoints in `./checkpoints`, if a folder is small than it should be, it may be damaged》
Maybe you can make sure LFS installed and then reuse the `git clone`  after deleting the model that originally downloaded from HuggingFace.

**Comment by shrinivasait** [comment]
Thank its solved now.

But i am getting now this.

"gradio.exceptions.Error: "Error Occurred! Please try again.\n Error communicating with OpenAI: HTTPConnectionPool(host='localhost', port=8001): Max retries exceeded with url: /v1/chat/completions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2b91f36050>: Failed to establish a new connection: [Errno 111] Connection refused'))"

Though i have added my openai key

**Comment by Zheng-Chong** [comment]
In this project, we did not use ChatGPT but used Vicuna to deploy as OpenAI API. To deploy Vicuna-13B in OpenAI API, follow this [instructions](https://github.com/lm-sys/FastChat/blob/main/docs/openai_api.md).

**Comment by shrinivasait** [comment]
I am facing difficulty in setting this vicuna.  The instruction given is not helping. Could you please help with that.

I am able install fastchat but, 
when i run python3 -m fastchat.serve.controller

i get this
2023-09-26 15:41:34 | INFO | controller | args: Namespace(host='localhost', port=21001, dispatch_method='shortest_queue', ssl=False)
2023-09-26 15:41:34 | ERROR | stderr | INFO:     Started server process [16279]
2023-09-26 15:41:34 | ERROR | stderr | INFO:     Waiting for application startup.
2023-09-26 15:41:34 | ERROR | stderr | INFO:     Application startup complete.
2023-09-26 15:41:34 | ERROR | stderr | INFO:     Uvicorn running on http://localhost:21001 (Press CTRL+C to quit)

**Comment by Zheng-Chong** [comment]
This means you have start the controller successfully. You can continue to deploy according to the guidance.

**Comment by shrinivasait** [comment]
Thanks, Its solved now.
