### ISSUE TITLE
is getting densepose working with stable diffusion (atuomatic 1111) actually possible? 

### ISSUE THREAD

**Issue by johndpope** [Zheng-Chong/FashionMatrix#6]
somebody tried but gave up 
https://civitai.com/models/120149/controlnet-for-densepose

**Comment by Zheng-Chong** [comment]
I have attempted to train ControlNet using DensePose, and it seems feasible, as you mentioned. However, in this project, we did not employ DensePose ControlNet; instead, we utilized DensePose as a segmentation prior. Could you elaborate further on the specific issues you would like to discuss?

**Comment by johndpope** [comment]
<img width="1514" alt="Screenshot 2023-11-30 at 10 36 57 pm" src="https://github.com/Zheng-Chong/FashionMatrix/assets/289994/dd81d3b4-20d8-4d05-b142-5042821b0512">



<img width="856" alt="Screenshot 2023-11-30 at 10 37 03 pm" src="https://github.com/Zheng-Chong/FashionMatrix/assets/289994/f2c38a76-8030-44b8-8caf-ed833ffb72b7">

I put the densepose trained model into stable diffusion - 
I select it from the controlnet - 
but I think someone (or ai) needs to build the preprocessor to get this actually working.
